### ISSUE TITLE
Thesaurus - not working to add Facets, Groups... in Django Admin

### ISSUE THREAD

**Issue by proteusos** [opensemanticsearch/open-semantic-search-server#10]
hi, i still can't get add Facets/Groups in Django Admin, or is there another way?
Is it possible to change the preconfigured groups like "Email", "Author",...??

i get this error when i add a Group in Django Admin. Before i add a Facet "test"
```

Request Method: | POST
-- | --
http://10.0.3.153/search-apps/admin/thesaurus/group/add/
1.10.7
AttributeError
'Facet' object has no attribute 'prefLabel'
/var/lib/opensemanticsearch/thesaurus/models.py in __str__, line 51
/usr/bin/python3
3.5.3

```

**Comment by Mandalka** [comment]
Thanks for your bugreport. The error after adding groups is fixed in source code and fix will be included in next weeks releases.

The "facets" or fields or properties author, email etc. are not "groups", but facets.

An enhanced interface for adding/changing/configure them will come next week: https://github.com/opensemanticsearch/open-semantic-search/issues/61

Groups are groups for entities for tagging additional tags for an entity so you can add multiple tags to this entities by being in a group instead of add multiple tags to each of this entities.
